# Objets énigmes

# TODO : Description des items
# TODO : Définition des mots à trouver + nom clé 
# TODO : Coordonnées X et Y
# TODO : Chemin réel des images

## Mémo : Contenant un rebus pour le remplissage de l'input final (Bouton mise en prod ou on rentre le chemin/path) 

book:
  name: book
  left: 37.3em #(left)
  top: 28.9em #(top)
  width: 7.4em
  height: 6em
  picture1: "http://3.238.70.10/images/book.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : RTFM ===> Le livre est une doc indigeste qu'il faut lire pour voir un mot sauter aux yeux (intrus)

labyrinth:
  name: labyrinth
  left: 98.6em #(left)
  top: 7.5em #(top)
  width: 16em
  height: 21.8em
  picture1: "http://3.238.70.10/images/labyrinth.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Le bon chemin est celui qui comporte autant de mots/objets que le nombre de merveilles du monde ===> Résultat : Mot à la sortie du bon chemin

kaamelott:
  name: kaamelott
  left: 4.8em #(left)
  top: 5.8em #(top)
  width: 36.3em
  height: 19.2em
  picture1: "http://3.238.70.10/images/kaamelott.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Description à l'image qui indique ce qu'il faut chercher d'après l'info du mémo ===> Résultat : Nom d'un personnage manquant ou région

carlin:
  name: carlin
  left: 42.5em #(left)
  top: 16.5 #(top)
  width: 9em
  height: 8em
  picture1: "http://3.238.70.10/images/carlin.svg"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Signature sur photo ou collier/médaille écrit à la mano Enigme ===> sur le mémo qui induit à cliquer sur tous les animaux ===> Résultat : Nom du carlin

code:
  name: code
  left: 54.5em #(left)
  top: 35.6em #(top)
  width: 2.5em
  height: 2.5em
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : Mon 5ème cause des bugs (mot ou pas, indice ou pas), enigme code complexe avec un mots qui ressort et qui casse tout Résultat : Mot qui fait bugguer

drawer_r:
  name: drawer_r
  left: 80.65em #(left)
  top: 59.6em #(top)
  width: 1.3em
  height: 1.3em
  border-radius: 50%
  picture1: "http://3.238.70.10/images/drawer.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : Mon 6ème est la clé .pem, enigme "ou est charlie" dans le tiroir en méga-bordel, la clé à son nom marqué dessus // Résultat : Nom de la clé

## Objet enigme finale (champ input)

button:
  name: button
  left: 105.4em #(left)
  top: 61.21em #(top)
  width: 1.8em
  height: 1.8em
  border-radius: 50%
  picture1: "http://3.238.70.10/images/button.png"
  status: 0
  type: inputable
  answer: /xxx/xxx/xxx/xxx/xxx/yyy.pem

## Objets Infos

memo_rebus:
  name: memo_rebus
  left: 61.5em #(left)
  top: 12.8em #(top)
  width: 7em
  height: 6.4em
  picture1: "http://3.238.70.10/images/memo_rebus.png"
  status: 0
  type: clickable
  description1: Charade indiquant le déroulement pour trouver le chemin absolu (5 mots + 1 nom.pem). Parfois l'énigme est sur le mémo, parfois le mémo indique ou est l'énigme.

memo:
  name: memo
  left: 72em #(left)
  top: 11.6em #(top)
  width: 6.8em
  height: 6.5em
  picture1: "http://3.238.70.10/images/memo.png"
  status: 0
  type: clickable
  description1: Des conneries humouristiques sur la vide des dev' !

duck:
  name: duck
  left: 82.3em #(left)
  top: 55em #(top)
  width: 3em
  height: 4em
  border-radius: 50%
  status: 0
  type: clickable
  description1: La méthode du canard en plastique (Paul le canard............)

mouse:
  name: mouse
  left: 77.5em #(left)
  top: 64em #(top)
  width: 2em
  height: 2em
  status: 0
  type: clickable
  description1: Blague "Il est chelou ce chat non ???"

cat:
  name: cat
  left: 46.6em #(left)
  top: 27.2em #(top)
  width: 4em
  height: 7.7em
  status: 0
  type: clickable
  description1: Descriptif chat japonais

rabbit:
  name: rabbit
  left: 45em #(left)
  top: 52em #(top)
  width: 3em 
  height: 5em
  status: 0
  type: clickable
  description1: Roger le lapin (+ Bla bla roger rabbit)

cup:
  name: cup
  left: 33.2em #(left)
  top: 32.9em #(top)
  width: 3em
  height: 2em
  status: 0
  type: clickable
  description1: Trophé du non-buggeur (de l'oeil du tigre du débugguage)

controller:
  name: controller
  left: 15.1em #(left)
  top: 55em #(top)
  width: 3.5em
  height: 1.4em
  status: 0
  type: clickable
  description1: "Y'a un projet à mettre en prod c'est pas l'heure de jouer !"
  
warhammer:
  name: warhammer
  left: 33.2em #(left)
  top: 58.5em #(top)
  width: 6.6em
  height: 8em
  status: 0
  type: clickable
  description1: "Une de mes passions c'est d'en acheter plein et de les mettre dans un tiroir sans les peindre ><"

car:
  name: car
  left: 22.5em #(left)
  top: 32.2em #(top)
  width: 9.4em
  height: 1.9em
  status: 0
  type: clickable
  description1: Blague RVLF

ie:
  name: ie
  left: 54.5em #(left)
  top: 43.6em #(top)
  width: 2.5em
  height: 2.5em
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

matrix:
  name: matrix
  left: 84.6em #(left)
  top: 18.3em #(top)
  width: 12.8em
  height: 18.3em
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Blague/clin d'oeil sur le nom de notre promo

coffee:
  name: coffee
  left: 52.7em #(left)
  top: 55.4em #(top)
  width: 2.6em 
  height: 2em
  status: 0
  type: clickable
  description1: Il est jamais vraiment ce café ?

paper:
  name: paper
  left: 66em #(left)
  top: 63em #(top)
  width: 6.8em 
  height: 3.2em
  status: 0
  type: clickable
  description1: Il est jamais vraiment ce café ?

drawer_l:
  name: drawer_l
  left: 46.74em #(left)
  top: 59.6em #(top)
  width: 1.3em
  height: 1.3em
  border-radius: 50%
  picture1: "http://3.238.70.10/images/drawer.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

banana:
  name: banana
  left: 57.8em #(left)
  top: 62.8em #(top)
  width: 1.5em 
  height: 3em
  status: 0
  type: clickable
  description1: Ref Mario Kart ?

exit:
  name: exit
  left: 94.25em #(left)
  top: 53.25em #(top)
  width: 9.1em 
  height: 3.3em
  status: 0
  type: clickable
  description1: Le week-end c'est par la !
