# Objets énigmes

# TODO : Description des items
# TODO : Définition des mots à trouver + nom clé 
# TODO : Coordonnées X et Y
# TODO : Chemin réel des images

## Mémo : Contenant un rebus pour le remplissage de l'input final (Bouton mise en prod ou on rentre le chemin/path) 

book:
  name: book
  x: 37.3em #(x)
  y: 28.9em #(y)
  width: 7.4em
  height: 6em
  picture1: "http://3.238.70.10/images/book.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : RTFM ===> Le livre est une doc indigeste qu'il faut lire pour voir un mot sauter aux yeux (intrus)

labyrinth:
  name: labyrinth
  x: 98.6em #(x)
  y: 7.5em #(y)
  width: 16em
  height: 21.8em
  picture1: "http://3.238.70.10/images/labyrinth.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Le bon chemin est celui qui comporte autant de mots/objets que le nombre de merveilles du monde ===> Résultat : Mot à la sortie du bon chemin

kaamelott:
  name: kaamelott
  x: 4.8em #(x)
  y: 5.8em #(y)
  width: 36.3em
  height: 19.2em
  picture1: "http://3.238.70.10/images/kaamelott.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Description à l'image qui indique ce qu'il faut chercher d'après l'info du mémo ===> Résultat : Nom d'un personnage manquant ou région

carlin:
  name: carlin
  x: 42.5em #(x)
  y: 16.5em #(y)
  width: 9em
  height: 8em
  picture1: "http://3.238.70.10/images/carlin.svg"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Signature sur photo ou collier/médaille écrit à la mano Enigme ===> sur le mémo qui induit à cliquer sur tous les animaux ===> Résultat : Nom du carlin

code:
  name: code
  x: 54.5em #(x)
  y: 35.6em #(y)
  width: 2.5em
  height: 2.5em
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : Mon 5ème cause des bugs (mot ou pas, indice ou pas), enigme code complexe avec un mots qui ressort et qui casse tout Résultat : Mot qui fait bugguer

drawer_r:
  name: drawer_r
  x: 80.65em #(x)
  y: 59.6em #(y)
  width: 1.3em
  height: 1.3em
  border-radius: 50%
  picture1: "http://3.238.70.10/images/drawer.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : Mon 6ème est la clé .pem, enigme "ou est charlie" dans le tiroir en méga-bordel, la clé à son nom marqué dessus // Résultat : Nom de la clé

## Objet enigme finale (champ input)

button:
  name: button
  x: 105.4em #(x)
  y: 61.21em #(y)
  width: 1.8em
  height: 1.8em
  border-radius: 50%
  picture1: "http://3.238.70.10/images/button.png"
  status: 0
  type: inputable
  answer: /xxx/xxx/xxx/xxx/xxx/yyy.pem

## Objets Infos

memo_rebus:
  name: memo_rebus
  x: 61.5em #(x)
  y: 12.8em #(y)
  width: 7em
  height: 6.4em
  picture1: "http://3.238.70.10/images/memo_rebus.png"
  status: 0
  type: clickable
  description1: Charade indiquant le déroulement pour trouver le chemin absolu (5 mots + 1 nom.pem). Parfois l'énigme est sur le mémo, parfois le mémo indique ou est l'énigme.

memo:
  name: memo
  x: 72em #(x)
  y: 11.6em #(y)
  width: 6.8em
  height: 6.5em
  picture1: "http://3.238.70.10/images/memo.png"
  status: 0
  type: clickable
  description1: Des conneries humouristiques sur la vide des dev' !

duck:
  name: duck
  x: 82.3em #(x)
  y: 55em #(y)
  width: 3em
  height: 4em
  border-radius: 50%
  status: 0
  type: clickable
  description1: La méthode du canard en plastique (Paul le canard............)

mouse:
  name: mouse
  x: 77.5em #(x)
  y: 64em #(y)
  width: 2em
  height: 2em
  status: 0
  type: clickable
  description1: Blague "Il est chelou ce chat non ???"

cat:
  name: cat
  x: 46.6em #(x)
  y: 27.2em #(y)
  width: 4em
  height: 7.7em
  status: 0
  type: clickable
  description1: Descriptif chat japonais

rabbit:
  name: rabbit
  x: 45em #(x)
  y: 52em #(y)
  width: 3em 
  height: 5em
  status: 0
  type: clickable
  description1: Roger le lapin (+ Bla bla roger rabbit)

cup:
  name: cup
  x: 33.2em #(x)
  y: 32.9em #(y)
  width: 3em
  height: 2em
  status: 0
  type: clickable
  description1: Trophé du non-buggeur (de l'oeil du tigre du débugguage)

controller:
  name: controller
  x: 15.1em #(x)
  y: 55em #(y)
  width: 3.5em
  height: 1.4em
  status: 0
  type: clickable
  description1: "Y'a un projet à mettre en prod c'est pas l'heure de jouer !"
  
warhammer:
  name: warhammer
  x: 33.2em #(x)
  y: 58.5em #(y)
  width: 6.6em
  height: 8em
  status: 0
  type: clickable
  description1: "Une de mes passions c'est d'en acheter plein et de les mettre dans un tiroir sans les peindre ><"

car:
  name: car
  x: 22.5em #(x)
  y: 32.2em #(y)
  width: 9.4em
  height: 1.9em
  status: 0
  type: clickable
  description1: Blague RVLF

ie:
  name: ie
  x: 54.5em #(x)
  y: 43.6em #(y)
  width: 2.5em
  height: 2.5em
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

matrix:
  name: matrix
  x: 84.6em #(x)
  y: 18.3em #(y)
  width: 12.8em
  height: 18.3em
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Blague/clin d'oeil sur le nom de notre promo

coffee:
  name: coffee
  x: 52.7em #(x)
  y: 55.4em #(y)
  width: 2.6em 
  height: 2em
  status: 0
  type: clickable
  description1: Il est jamais vraiment ce café ?

paper:
  name: paper
  x: 66em #(x)
  y: 63em #(y)
  width: 6.8em 
  height: 3.2em
  status: 0
  type: clickable
  description1: Il est jamais vraiment ce café ?

drawer_l:
  name: drawer_l
  x: 46.74em #(x)
  y: 59.6em #(y)
  width: 1.3em
  height: 1.3em
  border-radius: 50%
  picture1: "http://3.238.70.10/images/drawer.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

banana:
  name: banana
  x: 57.8em #(x)
  y: 62.8em #(y)
  width: 1.5em 
  height: 3em
  status: 0
  type: clickable
  description1: Ref Mario Kart ?

exit:
  name: exit
  x: 94.25em #(x)
  y: 53.25em #(y)
  width: 9.1em 
  height: 3.3em
  status: 0
  type: clickable
  description1: Le week-end c'est par la !
