# Objets énigmes

# TODO : Description des items
# TODO : Définition des mots à trouver + nom clé 
# TODO : Coordonnées X et Y
# TODO : Chemin réel des images

## Mémo : Contenant un rebus pour le remplissage de l'input final (Bouton mise en prod ou on rentre le chemin/path) 

book:
  name: book
  x: 37rem #(x)
  y: 28.9rem #(y)
  width: 7.4rem
  height: 5.8rem
  picture1: "http://3.238.70.10/images/book.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : RTFM ===> Le livre est une doc indigeste qu'il faut lire pour voir un mot sauter aux yeux (intrus)

labyrinth:
  name: labyrinth
  x: 98rem #(x)
  y: 7.5rem #(y)
  width: 16rem
  height: 21.6rem
  picture1: "http://3.238.70.10/images/labyrinth.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Le bon chemin est celui qui comporte autant de mots/objets que le nombre de merveilles du monde ===> Résultat : Mot à la sortie du bon chemin

kaamelott:
  name: kaamelott
  x: 4.75rem #(x)
  y: 5.8rem #(y)
  width: 36rem
  height: 19rem
  picture1: "http://3.238.70.10/images/kaamelott.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Description à l'image qui indique ce qu'il faut chercher d'après l'info du mémo ===> Résultat : Nom d'un personnage manquant ou région

carlin:
  name: carlin
  x: 42.1rem #(x)
  y: 16.5rem #(y)
  width: 9rem
  height: 8rem
  picture1: "http://3.238.70.10/images/carlin.svg"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Signature sur photo ou collier/médaille écrit à la mano Enigme ===> sur le mémo qui induit à cliquer sur tous les animaux ===> Résultat : Nom du carlin

code:
  name: code
  x: 54rem #(x)
  y: 35.4rem #(y)
  width: 2.5rem
  height: 2.5rem
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : Mon 5ème cause des bugs (mot ou pas, indice ou pas), enigme code complexe avec un mots qui ressort et qui casse tout Résultat : Mot qui fait bugguer

drawer_r:
  name: drawer_r
  x: 80.04rem #(x)
  y: 59.2rem #(y)
  width: 1.3rem
  height: 1.3rem
  border-radius: 50%
  picture1: "http://3.238.70.10/images/drawer.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

## Indice mémo : Mon 6ème est la clé .pem, enigme "ou est charlie" dans le tiroir en méga-bordel, la clé à son nom marqué dessus // Résultat : Nom de la clé

## Objet enigme finale (champ input)

button:
  name: button
  x: 104.55rem #(x)
  y: 60.75rem #(y)
  width: 1.8rem
  height: 1.8rem
  border-radius: 50%
  picture1: "http://3.238.70.10/images/button.png"
  status: 0
  type: inputable
  answer: /xxx/xxx/xxx/xxx/xxx/yyy.pem

## Objets Infos

memo_rebus:
  name: memo_rebus
  x: 61rem #(x)
  y: 12.8rem #(y)
  width: 7rem
  height: 6.4rem
  picture1: "http://3.238.70.10/images/memo_rebus.png"
  status: 0
  type: clickable
  description1: Charade indiquant le déroulement pour trouver le chemin absolu (5 mots + 1 nom.pem). Parfois l'énigme est sur le mémo, parfois le mémo indique ou est l'énigme.

memo:
  name: memo
  x: 71.5rem #(x)
  y: 11.6rem #(y)
  width: 6.8rem
  height: 6.5rem
  picture1: "http://3.238.70.10/images/memo.png"
  status: 0
  type: clickable
  description1: Des conneries humouristiques sur la vide des dev' !

duck:
  name: duck
  x: 81.6rem #(x)
  y: 54.6rem #(y)
  width: 3rem
  height: 4rem
  border-radius: 50%
  status: 0
  type: clickable
  description1: La méthode du canard en plastique (Paul le canard............)

mouse:
  name: mouse
  x: 77rem #(x)
  y: 63.3rem #(y)
  width: 2rem
  height: 2rem
  status: 0
  type: clickable
  description1: Blague "Il est chelou ce chat non ???"

cat:
  name: cat
  x: 46.1rem #(x)
  y: 27rem #(y)
  width: 4rem
  height: 7.7rem
  status: 0
  type: clickable
  description1: Descriptif chat japonais

rabbit:
  name: rabbit
  x: 44.8rem #(x)
  y: 51.5rem #(y)
  width: 3rem 
  height: 5rem
  status: 0
  type: clickable
  description1: Roger le lapin (+ Bla bla roger rabbit)

cup:
  name: cup
  x: 33rem #(x)
  y: 32.6rem #(y)
  width: 2.8rem
  height: 2.1rem
  status: 0
  type: clickable
  description1: Trophé du non-buggeur (de l'oeil du tigre du débugguage)

controller:
  name: controller
  x: 14.9rem #(x)
  y: 54.5rem #(y)
  width: 3.5rem
  height: 1.4rem
  status: 0
  type: clickable
  description1: "Y'a un projet à mettre en prod c'est pas l'heure de jouer !"
  
warhammer:
  name: warhammer
  x: 32.95rem #(x)
  y: 58.5rem #(y)
  width: 6.6rem
  height: 7.5rem
  status: 0
  type: clickable
  description1: "Une de mes passions c'est d'en acheter plein et de les mettre dans un tiroir sans les peindre ><"

car:
  name: car
  x: 22.2rem #(x)
  y: 32rem #(y)
  width: 9.4rem
  height: 1.9rem
  status: 0
  type: clickable
  description1: Blague RVLF

ie:
  name: ie
  x: 54rem #(x)
  y: 43.1rem #(y)
  width: 2.5rem
  height: 2.5rem
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

matrix:
  name: matrix
  x: 83.9rem #(x)
  y: 18.16rem #(y)
  width: 12.8rem
  height: 18.3rem
  picture1: "http://3.238.70.10/images/code.png"
  status: 0
  type: clickable
  description1: Blague/clin d'oeil sur le nom de notre promo

coffee:
  name: coffee
  x: 52.3rem #(x)
  y: 54.9rem #(y)
  width: 2.6rem 
  height: 2rem
  status: 0
  type: clickable
  description1: Il est jamais froid ce café ?

paper:
  name: paper
  x: 65.5rem #(x)
  y: 62.5rem #(y)
  width: 6.8rem 
  height: 3.2rem
  status: 0
  type: clickable
  description1: Une envie pressante ?

drawer_l:
  name: drawer_l
  x: 46.35rem #(x)
  y: 59.2rem #(y)
  width: 1.3rem
  height: 1.3rem
  border-radius: 50%
  picture1: "http://3.238.70.10/images/drawer.png"
  status: 0
  type: clickable
  description1: Lorem ipsum dolor sit amet consectetur adipisicing elit. Sit molestias distinctio corrupti autem doloremque beatae consequatur voluptatum. Reiciendis, eos. Laudantium voluptatibus nam itaque aliquid cupiditate hic laborum accusantium sed modi!
    Recusandae dolorem rem, officia perspiciatis dignissimos ex nemo quae facilis sunt delectus totam repellendus maxime, soluta dolores nihil aspernatur explicabo libero placeat! Corrupti quia expedita tenetur alias officiis, dolor eum?

banana:
  name: banana
  x: 57.3rem #(x)
  y: 62.4rem #(y)
  width: 1.5rem 
  height: 3rem
  status: 0
  type: clickable
  description1: Ref Mario Kart ?

exit:
  name: exit
  x: 93.5rem #(x)
  y: 52.85rem #(y)
  width: 9.1rem 
  height: 3.3rem
  status: 0
  type: clickable
  description1: Le week-end c'est par la !
